apiVersion: skaffold/v1alpha2
kind: Config

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - imageName: sunfmin/app1
      workspace: .
      docker:
        dockerfilePath: ./app1/Dockerfile
    - imageName: sunfmin/app2
      workspace: .
      docker:
        dockerfilePath: ./app2/Dockerfile
  local:
    skipPush: true

deploy:
  kubectl:
    manifests:
      - ./k8s/*.yaml
