---
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
  labels:
    app: app1-svc
spec:
  ports:
    - port: 9090
      name: app1-port
      targetPort: 8080
  selector:
    app: app1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: sunfmin/app1
      imagePullSecrets:
      - name: dockerhub
