---
apiVersion: v1
kind: Service
metadata:
  name: app2-svc
  labels:
    app: app2-svc
spec:
  ports:
    - port: 9091
      name: app2-port
      targetPort: 8080
  selector:
    app: app2
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: sunfmin/app2
      imagePullSecrets:
      - name: dockerhub
